name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    paths:
      - '**.java'
      - 'gradle**'
      - 'build.gradle'
  pull_request:
    paths:
      - '**.java'
      - 'gradle**'
      - 'build.gradle'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Check code style with Spotless
      id: spotless_check
      run: ./gradlew spotlessCheck

    - name: Execute Gradle build
      run: ./gradlew build
    - name: Upload built jar to artifacts
      # if: github.event_name == 'push'
      uses: actions/upload-artifact@v3
      with:
        name: sujuk-dev-build
        path: ./build/libs/*.jar
